# Generated by Django 3.2.20 on 2023-08-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lstm_api', '0016_rename_token_user_ftoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ftoken',
            new_name='token',
        ),
    ]
