# Generated by Django 3.2.20 on 2023-10-16 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lstm_api', '0017_rename_ftoken_user_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('title', models.TextField(blank=True, null=True, verbose_name='일기 제목')),
                ('content', models.TextField(blank=True, null=True, verbose_name='일기 내용')),
                ('photo', models.TextField(blank=True, null=True, verbose_name='사진 경로')),
                ('userbaby_relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lstm_api.userbabyrelationship')),
            ],
        ),
    ]
