# Generated by Django 3.2.22 on 2023-10-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstm_api', '0018_dailynote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailynote',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y-%m-%d/', verbose_name='사진'),
        ),
    ]
